version: '3.7'

services:
  n8n:
    image: geovanedcs/n8n-puppeteer:latest
    container_name: n8n
    restart: always
    environment:
      # Configuração básica
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://geedcs.duckdns.org/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # APENAS PUPPETEER (mais limpo)
      - NODE_FUNCTION_ALLOW_EXTERNAL=puppeteer,puppeteer-extra,puppeteer-extra-plugin-stealth,puppeteer-extra-plugin-user-preferences,puppeteer-extra-plugin-user-data-dir

      # --- CONFIGURAÇÕES DE PERFORMANCE E SEGURANÇA ---
      - N8N_ENCRYPTION_KEY='ff0h/OkaDXGNsmnPLarTFK6Cx0N4cDlg'
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_TRUST_PROXY=true
      - DB_SQLITE_POOL_SIZE=1
      - N8N_RUNNERS_ENABLED=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - NODE_OPTIONS=--max-old-space-size=384
      - N8N_RUNNERS_MAX_OLD_SPACE_SIZE=384

      # Desabilita recursos não essenciais para economizar RAM
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_COMMUNITY_PACKAGES_ENABLED=false
      - N8N_LOG_LEVEL=warn
      - N8N_TABLES_ENABLED=false
      # Chromium do sistema para Puppeteer
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

      # Limita execuções simultâneas
      - EXECUTIONS_PROCESS=main
      # Mantém histórico de execuções para debug
      - EXECUTIONS_DATA_PRUNE=false
      - EXECUTIONS_DATA_MAX_AGE=1

      # Playwright/Puppeteer: sempre feche o browser após uso nos seus scripts

    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    deploy:
      resources:
        limits:
          memory: 700m
        reservations:
          memory: 256m

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - n8n
    networks:
      - n8n-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - n8n-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - TZ=America/Sao_Paulo
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - n8n-network

volumes:
  n8n_data:
    driver: local

networks:
  n8n-network:
    driver: bridge