name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/n8n-app
            git pull origin main
            # Remove todos os containers baseados nas imagens problemáticas
            docker ps -a --filter ancestor=certbot/certbot --format '{{.ID}}' | xargs -r docker rm -f
            docker ps -a --filter ancestor=containrrr/watchtower --format '{{.ID}}' | xargs -r docker rm -f
            docker rmi certbot/certbot containrrr/watchtower || true
            docker-compose pull
            docker-compose up -d
